name: 🚀 Feature proposal for the JSA
description: I have a suggestion (and may want to implement it)!
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        You have an idea how to improve the site? That's awesome!
        Before submitting, please have a look at the existing issues if there's already
        something related to your suggestion.
  - type: textarea
    attributes:
      label: 'Enter your suggestions in details:'
      placeholder: |
       How its work?
    validations:
      required: true